cut-body-after = "---"
delete-merged-branches = true

status = [
    "Full Tests (ubuntu-latest)",
    "Full Tests (windows-latest)",
    "Full Tests (macos-latest)",
]

pr-status = [
    "license/cla",
]
