version: 1
update_configs:
  - package_manager: rust:cargo
    directory: /
    update_schedule: live

    default_labels:
      - "type: chore"
    allowed_updates:
      - match:
          update_type: all
    version_requirement_updates: auto
