# Heavily inspired by the rust-analyzer CI configuration
# Checks done here should be a strict superset of pr.yaml!

name: Bors CI

on:
  push:
    branches:
      - staging
      - trying

env:
  CARGO_INCREMENTAL: 0

jobs:

  tests:
    name: Full Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: beta
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: Cache target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-rustc-${{ steps.toolchain.outputs.rustc_hash }}-target-${{ hashFiles('**/Cargo.lock') }}
          # We deliberately don't fall back to old caches to avoid including unused dependencies' artifacts in the cache

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --locked --no-run

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --frozen --no-fail-fast

      - name: Check formatting
        if: matrix.os == 'ubuntu-latest' && !cancelled()
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check warnings
        if: matrix.os == 'ubuntu-latest' && !cancelled()
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --locked -- -D warnings

      - name: Prepare cache
        uses: actions-rs/cargo@v1
        if: "!steps.cache.outputs.cache-hit"
        with:
          command: xtask
          args: clean

      - name: (Windows) Prepare cache
        if: matrix.os == 'windows-latest' && !steps.cache.outputs.cache-hit
        run: Remove-Item ./target/debug/xtask.exe, ./target/debug/deps/xtask.exe -ErrorAction Ignore
